### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by mgiroux** [tdscientist/ShelfView-iOS#3]
As you can see from the images, it does not support iPhone X very well

![screen shot 2017-10-10 at 1 23 52 pm](https://user-images.githubusercontent.com/4205308/31400652-638101d8-adbe-11e7-9110-f21fc1135350.png)

![screen shot 2017-10-10 at 1 23 59 pm](https://user-images.githubusercontent.com/4205308/31400651-63752106-adbe-11e7-9b9a-03cdf4f09c7d.png)

**Comment by tdscientist** [comment]
Use the shelfView within the safe area layout.
